fail_fast: false

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes ]
      - id: ruff-format

