name: Python Job

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.9"
      run:
        required: true
        type: string
      artifact:
        type: string
        default: ''
        required: false
      artifact_path:
        type: string
        default: ''
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: "${{ github.head_ref || github.ref }}"

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: ${{ inputs.python-version }}

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,test]

      - name: Run Command
        run: |
          ${{ inputs.run }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ inputs.artifact != '' && inputs.artifact_path != '' }}
        with:
          name: ${{ inputs.artifact }}
          path: ${{ inputs.artifact_path }}
          if-no-files-found: ignore

